version: '3.8'

services:
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mi-mysql-container:3306/notification_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 405454
      REDIS_HOST: redis-notifications
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - app-chat

  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mi-mysql-container:3306/chat_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 405454
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - app-chat

  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mi-mysql-container:3306/profile_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 405454
    networks:
      - app-chat

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      PROFILE_SERVICE_URL: http://profile-service:8088
      NOTIFICATION_SERVICE_URL: ws://notification-service:8084
      CHAT_SERVICE_URL: ws://chat-service:8085
      MEDIA_SERVICE_URL: http://media-service:8086
      MEDIA_SERVICE_WS_URL: ws://media-service:8086
      REDIS_HOST: redis-notifications
    networks:
      - app-chat

networks:
  app-chat:
    external: true  # Indica que la red ya existe