spring.application.name=connection-service
server.port=8083

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}

logging.level.org.hibernate.sql=off
spring.jpa.show-sql=false

connection.service.instance.id=${INSTANCE_ID}
chat.service.url=${CHAT_SERVICE_URL:http://localhost:8085}
